### ISSUE TITLE
Timeout when PUT attempted on a 0 bytes file

### ISSUE THREAD

**Issue by createandcode** [christophschlosser/drone-ftps#11]
Hey @christophschlosser - thanks for this plugin!

Just getting up and running with Drone :)

The issue I'm experiencing is quite similar to this
https://github.com/lavv17/lftp/issues/420

My jobs are timing out after an hour.

As soon as I add something to the offending file the job can be completed.

Target ftp server is Pure-FTPD configured via CentMin Mod
https://centminmod.com/ftp.html

Here's my .drone.yml

```pipeline:
  deploy:
    image: cschlosser/drone-ftps
    hostname: snip
    secrets: [ ftp_username, ftp_password ]
    dest_dir: /foo/
    secure: true
    verify: false
    exclude:
    - ^\.git/$
    - ^\.gitignore$
    - ^\.drone.yml$```

Not sure if this is something that should be handled at the server end? 
Is there some way of ensuring the job completes or has a lower timeout value for failure?

**Comment by cschlosser** [comment]
Hey @createandcode :)

Thanks, really appreciated!

This is a problem with LFTP, the ftp client used by this plugin.

It was fixed in february but there has been no new release since october last year.
Until there is a new release I guess we have to live with this.

Sorry I couldn't be of more help here.

There is of course always the possibility that someone designs a workaround for this plugin as described in https://github.com/lavv17/lftp/issues/420#issuecomment-360188229. Unfortunately I have no time at the moment to do this :( If you think you're up to it feel free to give it a shot!

**Comment by createandcode** [comment]
ah ok! I hadn't realized this plugin was actually using LFTP :)

No worries - for now I solved the issue by simply merging the empty file with a different file. 

Re: workaround - it's probably a bit beyond my pay grade right now :)

Thanks for your work on this plugin - it works great!

**Comment by SGTGunner** [comment]
@createandcode and @christophschlosser. I don't have the issue as I forked the code and went and remove the `lftp \` reference and then added the following line in the Dockerfile `RUN apk add 'lftp>4.8.4' --updated-cache --repository http://nl.alpinelinux.org/alpine/edge/main` All is working well now.

**Comment by cschlosser** [comment]
Using the alpine:edge base image this may not be necessary.

Maybe you could test the new image @SGTGunner  @createandcode if it now works for you

**Comment by cschlosser** [comment]
As there's no reply I'm closing this.
